framework:
    assets:         true
    ide: sublime
#    esi:             ~
#    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
#    router:
#        resource: "%kernel.root_dir%/config/routing.yml"
#        strict_requirements: ~
    form:            ~
    csrf_protection: ~
#    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
