services:
    _defaults:
        autowire: true
        bind:
            $bankAccount: '%bankAccount%'
        # for tests
        public: true

    TomasVotruba\Website\Posts\Year2018\ParameterToSymfonyController\Controller\:
        resource: ../Controller
